config/routes.rb
Clippy::Application.routes.draw do

  # resources :oauth_clients
  # 
  # match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request
  # 
  # match '/oauth/token',         :to => 'oauth#token',         :as => :token
  # 
  # match '/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token
  # 
  # match '/oauth/request_token', :to => 'oauth#request_token', :as => :request_token
  # 
  # match '/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize
  # 
  # match '/oauth',               :to => 'oauth#index',         :as => :oauth
  # 
  # resources :authentications
  
  devise_for :users, :controllers => { :registrations => 'registrations' } do
    get "/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get "/sign_in" => "devise/sessions#new", :as => :new_user_session
  end
  
  # Sample resource route within a namespace:
  namespace :api do
    namespace :v1  do
      match "data" => "data#show"
      resources :users, :only => [:show] do
        member do
          get 'feed'
          post 'clip'
        end
      end
      resources :clips
    end
  end

  resources :clips, :only =>[:create, :destroy]
  resources :users, :only => [:show]
  
  match '/auth/:provider/callback', to: 'authentications#create'
  # match '/auth/failure', :to => 'authentications#failure'
  # 
  # # Provider stuff
  # match '/auth/clippit/authorize' => 'auth#authorize'
  # match '/auth/clippit/access_token' => 'auth#access_token'
  # match '/auth/clippit/user' => 'auth#user'
  # match '/oauth/token' => 'auth#access_token'
  
  #match "/signout" => "sessions#destroy", :as => :signout

  #get "home/index"

  root :to => 'home#index'

end

app/models/clip.rb
class Clip < ActiveRecord::Base
  attr_accessible :content, :url
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true
  validates :url, presence: true
  
  default_scope order: 'clips.created_at DESC'
end

app/controllers/api/v1/clips_controller.rb
class Api::V1::ClipsController < Api::V1::BaseController
  
  def index
    @clips = Clip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clips }
    end
  end

  def create
    @clip = current_user.clips.build(params[:clip])

    respond_to do |format|
      if @clip.save
        format.html { redirect_to root_path, notice: 'Clip was successfully created.' }
        format.json { render json: @clip, status: :created, location: @clip }
      else
        @feed_items = []
        format.html { render action: "new" }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @clip = Clip.find(params[:id])
    @clip.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Clip was deleted.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :correct_user,   only: :destroy
  
  # GET /clips
  # GET /clips.json
  def index
    @clips = Clip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clips }
    end
  end

  # GET /clips/1
  # GET /clips/1.json
  # def show
  #   @clip = Clip.find(params[:id])
  # 
  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @clip }
  #   end
  # end

  # GET /clips/new
  # GET /clips/new.json
  # def new
  #   @clip = Clip.new
  # 
  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @clip }
  #   end
  # end

  # GET /clips/1/edit
  # def edit
  #   @clip = Clip.find(params[:id])
  # end

  # POST /clips
  # POST /clips.json
  def create
    @clip = current_user.clips.build(params[:clip])
    #@clip = Clip.new(params[:clip])

    respond_to do |format|
      if @clip.save
        format.html { redirect_to root_path, notice: 'Clip was successfully created.' }
        format.json { render json: @clip, status: :created, location: @clip }
      else
        @feed_items = []
        format.html { render action: "new" }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clips/1
  # PUT /clips/1.json
  # def update
  #   @clip = Clip.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @clip.update_attributes(params[:clip])
  #       format.html { redirect_to @clip, notice: 'Clip was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @clip.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @clip = Clip.find(params[:id])
    @clip.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Clip was deleted.' }
      format.json { head :no_content }
    end
  end
  
  private

    def correct_user
      @clip = current_user.clips.find_by_id(params[:id])
      redirect_to root_path if @clip.nil?
    end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/_clip.html.erb
<li>
	<%= link_to clip.url %>
	<p><%= clip.content %></p>
	<time class="timestamp">Posted <%= time_ago_in_words(clip.created_at) %> ago.</time>
	<% if current_user == clip.user %>
    <%= link_to "delete", clip, method:  :delete,
                                     confirm: "You sure?",
                                     title:   clip.content %>
  <% end %>
</li>

app/views/clips/_form.html.erb
<%= form_for(@clip) do |f| %>
  <% if @clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
      <% @clip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clips/edit.html.erb
<h1>Editing clip</h1>

<%= render 'form' %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', clips_path %>

app/views/clips/index.html.erb
<h1>Listing clips</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clips.each do |clip| %>
  <tr>
    <td><%= clip.url %></td>
    <td><%= clip.content %></td>
    <td><%= link_to 'Show', clip %></td>
    <td><%= link_to 'Edit', edit_clip_path(clip) %></td>
    <td><%= link_to 'Destroy', clip, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clip', new_clip_path %>

app/views/clips/new.html.erb
<h1>New clip</h1>

<%= render 'form' %>

<%= link_to 'Back', clips_path %>

app/views/clips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @clip.url %>
</p>

<p>
  <b>Content:</b>
  <%= @clip.content %>
</p>


<%= link_to 'Edit', edit_clip_path(@clip) %> |
<%= link_to 'Back', clips_path %>